name:                photograph-pixela
version:             0.1.0.0
github:              "kakkun61/photograph-pixela"
license:             BSD3
author:              "Kazuki Okamoto"
maintainer:          "kazuki.okamoto@kakkun61.com"
copyright:           "Kazuki Okamoto"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/kakkun61/photograph-pixela#readme>

dependencies:
- base >= 4.7 && < 5
- bytestring
- directory
- filepath
- optparse-declarative
- pixela
- process
- pureMD5

library:
  source-dirs: src

executables:
  photograph-pixela:
    main:                Main.hs
    source-dirs:         app
    ghc-options:         []
    dependencies:
    - photograph-pixela

tests:
  photograph-pixela-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:         []
    dependencies:
    - photograph-pixela
