name:                photograph-pixela
version:             0.1.0.0
github:              "kakkun61/photograph-pixela"
license:             BSD3
author:              "Kazuki Okamoto"
maintainer:          "kazuki.okamoto@kakkun61.com"
copyright:           "Kazuki Okamoto"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/kakkun61/photograph-pixela#readme>

dependencies:
- base >= 4.7 && < 5
- aeson
- bytestring
- cereal
- data-default-class
- directory
- filepath
- hsexif
- lens
- lens-aeson
- optparse-declarative
- pixela
- process
- pureMD5
- scientific
- text
- time
- yaml

ghc-options:
  - -Wall
  - -Wcompat
  - -fwarn-tabs
  - -fwarn-incomplete-record-updates
  - -fwarn-monomorphism-restriction
  - -fwarn-unused-do-bind

executables:
  photograph-pixela:
    main:                Main.hs
    source-dirs:         app
